### ISSUE TITLE
Error calculating minified sizes

### ISSUE THREAD

**Issue by sybrendotinga** [FormidableLabs/electron-webpack-dashboard#31]
During development I don't minify or gzip my files. That is probably why I get this error. 

![schermafbeelding 2017-08-31 om 11 23 22](https://user-images.githubusercontent.com/14016492/29916376-d9103008-8e3e-11e7-81ff-fa4706a28812.png)

**Comment by rawrmonstar** [comment]
Thanks for the report @sybrendotinga! There is a chance that this bug was resolved upstream in [FormidableLabs/inspectpack](https://github.com/FormidableLabs/inspectpack) can you reinstall and verify the bug is still present?

If so, can you provide a demo repo and steps to reproduce this error to help us debug the problem?

Thanks 😄

**Comment by sybrendotinga** [comment]
Sorry for my belated response. I was away for a holiday. The update seems to have fixed this issue. 

![schermafbeelding 2017-10-09 om 15 46 40](https://user-images.githubusercontent.com/14016492/31341264-450c2184-ad09-11e7-9fc1-dbfa547131b7.png)
